### PR TITLE
TypeScript improvements for IDEs

### PR DESCRIPTION
**Pull request by ties-s**
This PR will:
- enable generating typings files in /dist
- set the `main` property of `package.json` to `./dist/BunqJSClient.js`
- set the `types` property of `package.json` to `./dist/BunqJSClient.d.ts` and removes the `typings` as they are interchangeable.
- prevent committing build files to git by adding `/dist` to `.gitignore`, this prevents cluttering commits with build files
- prevent publishing source files to npm by adding `/src` to `.npmignore` this keeps download size while installing the package low
- moves `@types/*` dependencies to `devDependencies` because they are only needed during development

### CODE REVIEW

**Comment by Crecket** [comment]
Thanks 👍 I have some basic Typescript experience but setting up the  types correctly was giving me a ton of issues when I tried it early on.

**Comment by ties-s** [comment]
This should enable support for auto complete in VSCode and other editors.

You may also want to move `@babel/*` to `devDependencies`. As far as I know they also only needed for building.

**Comment by ties-s** [comment]
Will you publish to npm or should I install from the repo for now?

**Comment by Crecket** [comment]
I'll publish it now 👍

**Comment by ties-s** [comment]
I think you forgot to build before publishing

**Comment by Crecket** [comment]
Should be good now on 0.35.2, it looks like the npmignore file also needs to include a bunch of the files/folders listed in the gitignore file.

**Pull request merged**
